### ISSUE TITLE
Cannot read property 'length' of undefined (Average Band Powers)

### ISSUE THREAD

**Issue by yahyawasim97** [pwstegman/bci.js#8]
I am loading an edf using:
bci.loadEDF
In return I am getting an object that contains a channel property. Each channel contains samples, I am passing each of these samples to bci.averageBandPowers but getting this error:
TypeError: Cannot read property 'length' of undefined
    at signalBandPower (C:\Users\HP\Desktop\projects\driverDrowsiness\node_modules\bcijs\lib\math\signalBandPower.js:49:41)
    at Object.averageBandPowers (C:\Users\HP\Desktop\projects\driverDrowsiness\node_modules\bcijs\lib\math\averageBandPowers.js:25:29)       
    at getData (C:\Users\HP\Desktop\projects\driverDrowsiness\index.js:11:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

P.S In channels.sample I am getting a 1d array rather than the 2d one in bci.loadedf
This is my edf file

**Comment by yahyawasim97** [comment]
const bci = require('bcijs');

let samples;
const getData =async()=>{
    let a = await bci.loadEDF('awais.md.edf');
        samples =[...a.channels[0].samples];
        console.log(a)
        try{

            let feature = await bci.averageBandPowers(a.channels, 256, ['alpha','beta']);
            console.log(feature);
        }catch(e){
            console.log(e)
        }

}
getData();

**Comment by pwstegman** [comment]
Looks like the documentation for loadEDF needed updating. I've corrected it now. Each channel is an object that has a 1D array of samples for that channel, so passing `a.channels` into averageBandPowers will throw an error. I've modified your code to get it working. Give this a try:


```javascript
const bci = require('bcijs');

let samples;

const getData = () => {
    let edf = bci.loadEDF('awais.md.edf');

    // Grab the samples from each channel
    samples = edf.channels.map(channel => channel.samples);

    // Transpose so channels are columns and samples are rows (the format averageBandPower expects)
    samples = bci.transpose(samples);
    
    let feature = bci.averageBandPowers(samples, 256, ['alpha','beta']);
    console.log(feature);
}

getData();
```

**Comment by yahyawasim97** [comment]
Thanks alot man! It works!
